/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks;

import java.util.*;
import java.time.*;

import com.fasterxml.jackson.annotation.*;


// ----------- << imports@AAAAAAFp+P/bU5PiTxE= >>
// ----------- >>

@JsonIgnoreProperties(ignoreUnknown = true)
// ----------- << class.annotations@AAAAAAFp+P/bU5PiTxE= >>
// ----------- >>
public class Address {
    // ----------- << attribute.annotations@AAAAAAFp+P/bU5Pjd1g= >>
    // ----------- >>
    private String city;

    // ----------- << attribute.annotations@AAAAAAFp+P/bU5PkcmY= >>
    // ----------- >>
    private String addressLine1;

    // ----------- << attribute.annotations@AAAAAAFp+P/bU5PlzrA= >>
    // ----------- >>
    private String addressLine2;

    // ----------- << attribute.annotations@AAAAAAFp+P/bU5PmP7w= >>
    // ----------- >>
    private String regionCode;

    // ----------- << attribute.annotations@AAAAAAFp+P/bU5Pn1fo= >>
    // ----------- >>
    private String regionDisplay;

    // ----------- << attribute.annotations@AAAAAAFp+P/bU5PopwA= >>
    // ----------- >>
    private String postalCode;

    // ----------- << attribute.annotations@AAAAAAFp+P/bU5Ppb5c= >>
    // ----------- >>
    private String country;

    public String getCity() {
        return city;
    }

    public String getAddressLine1() {
        return addressLine1;
    }

    public String getAddressLine2() {
        return addressLine2;
    }

    public String getRegionCode() {
        return regionCode;
    }

    public String getRegionDisplay() {
        return regionDisplay;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public String getCountry() {
        return country;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    public void setRegionDisplay(String regionDisplay) {
        this.regionDisplay = regionDisplay;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public void setCountry(String country) {
        this.country = country;
    }

// ----------- << class.extras@AAAAAAFp+P/bU5PiTxE= >>
// ----------- >>
}