/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks;

import java.util.*;
import java.time.*;


import com.archetypesoftware.fastspring.webhooks.EventVisitor;
import com.archetypesoftware.fastspring.webhooks.WebHookEvent;
// ----------- << imports@AAAAAAFqAbm1y/fsvU8= >>
// ----------- >>

/**
* A placeholder for webhook events, as sent by the FastSpring.
*/

// ----------- << class.annotations@AAAAAAFqAbm1y/fsvU8= >>
// ----------- >>
public class Notification {
    // ----------- << attribute.annotations@AAAAAAFqAbqg0fgZoVQ= >>
    // ----------- >>
    private List<WebHookEvent> events = new ArrayList<>();

    public List<WebHookEvent> getEvents() {
        return events;
    }

    public void linkEvents(WebHookEvent _events) {
        if (_events != null) {
            getEvents().add(_events);
        }
    }

    public void unlinkEvents(WebHookEvent _events) {
        if (_events != null) {
            getEvents().remove(_events);
        }
    }

    public void unlinkEvents(Iterator<WebHookEvent> it) {
        it.remove();
    }

    /**
    * @param visitor
    */

    // ----------- << method.annotations@AAAAAAFqAbrMCfh3ZdQ= >>
    // ----------- >>
    public void process(EventVisitor visitor) {
    // ----------- << method.body@AAAAAAFqAbrMCfh3ZdQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAFqAbm1y/fsvU8= >>
// ----------- >>
}