/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFp+P/bQJFfKH8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp+P/bQJFfKH8= >>
// ----------- >>
public class SubscriptionDeactivatedEvent extends WebHookEvent {
// ----------- << class.extras@AAAAAAFp+P/bQJFfKH8= >>
// ----------- >>
}