/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks.events;

import java.util.*;
import java.time.*;

import com.fasterxml.jackson.annotation.*;


// ----------- << imports@AAAAAAFqFaCWowh/VVQ= >>
// ----------- >>

@JsonIgnoreProperties(ignoreUnknown = true)
// ----------- << class.annotations@AAAAAAFqFaCWowh/VVQ= >>
// ----------- >>
public class OrderItem {
    // ----------- << attribute.annotations@AAAAAAFqFaCWowiBDZ8= >>
    // ----------- >>
    private String product;

    // ----------- << attribute.annotations@AAAAAAFqFaCWowiCHts= >>
    // ----------- >>
    private int quantity;

    // ----------- << attribute.annotations@AAAAAAFqFaCWowiDIYw= >>
    // ----------- >>
    private String display;

    // ----------- << attribute.annotations@AAAAAAFqFaCWpAiEFdk= >>
    // ----------- >>
    private float subtotal;

    // ----------- << attribute.annotations@AAAAAAFqFaCWpAiFlBE= >>
    // ----------- >>
    private String subtotalDisplay;

    // ----------- << attribute.annotations@AAAAAAFqFaCWpAiGoo0= >>
    // ----------- >>
    private float subtotalInPayoutCurrency;

    // ----------- << attribute.annotations@AAAAAAFqFaCWpAiHEiw= >>
    // ----------- >>
    private float discount;

    // ----------- << attribute.annotations@AAAAAAFqFaCWpQiIDSs= >>
    // ----------- >>
    private String discountDisplay;

    // ----------- << attribute.annotations@AAAAAAFqFaCWpQiJfrI= >>
    // ----------- >>
    private float discountInPayoutCurrency;

    // ----------- << attribute.annotations@AAAAAAFqFasg9hkWSgM= >>
    // ----------- >>
    private SubscriptionInfo subscription;

    public String getProduct() {
        return product;
    }

    public int getQuantity() {
        return quantity;
    }

    public String getDisplay() {
        return display;
    }

    public float getSubtotal() {
        return subtotal;
    }

    public String getSubtotalDisplay() {
        return subtotalDisplay;
    }

    public float getSubtotalInPayoutCurrency() {
        return subtotalInPayoutCurrency;
    }

    public float getDiscount() {
        return discount;
    }

    public String getDiscountDisplay() {
        return discountDisplay;
    }

    public float getDiscountInPayoutCurrency() {
        return discountInPayoutCurrency;
    }

    public SubscriptionInfo getSubscription() {
        return subscription;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public void setDisplay(String display) {
        this.display = display;
    }

    public void setSubtotal(float subtotal) {
        this.subtotal = subtotal;
    }

    public void setSubtotalDisplay(String subtotalDisplay) {
        this.subtotalDisplay = subtotalDisplay;
    }

    public void setSubtotalInPayoutCurrency(float subtotalInPayoutCurrency) {
        this.subtotalInPayoutCurrency = subtotalInPayoutCurrency;
    }

    public void setDiscount(float discount) {
        this.discount = discount;
    }

    public void setDiscountDisplay(String discountDisplay) {
        this.discountDisplay = discountDisplay;
    }

    public void setDiscountInPayoutCurrency(float discountInPayoutCurrency) {
        this.discountInPayoutCurrency = discountInPayoutCurrency;
    }

    public void setSubscription(SubscriptionInfo subscription) {
        this.subscription = subscription;
    }

    public void linkSubscription(SubscriptionInfo _subscription) {
        setSubscription(_subscription);
    }

    public void unlinkSubscription() {
        setSubscription(null);
    }

// ----------- << class.extras@AAAAAAFqFaCWowh/VVQ= >>

    @Override
    public String toString() {
        return "OrderItem{" +
                "product='" + product + '\'' +
                ", quantity=" + quantity +
                ", display='" + display + '\'' +
                ", subtotal=" + subtotal +
                ", subtotalDisplay='" + subtotalDisplay + '\'' +
                ", subtotalInPayoutCurrency=" + subtotalInPayoutCurrency +
                ", discount=" + discount +
                ", discountDisplay='" + discountDisplay + '\'' +
                ", discountInPayoutCurrency=" + discountInPayoutCurrency +
                ", subscription=" + subscription +
                '}';
    }

// ----------- >>
}