/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks.events;

import java.util.*;
import java.time.*;

import com.fasterxml.jackson.annotation.*;

import com.archetypesoftware.fastspring.webhooks.EventPayload;
// ----------- << imports@AAAAAAFqFYFscvvxewM= >>
import com.archetypesoftware.jackson.DateDeserializers;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
// ----------- >>

// ----------- << class.annotations@AAAAAAFqFYFscvvxewM= >>
// ----------- >>
public class OrderCompletedPayload extends EventPayload {
    @JsonProperty("id")
    // ----------- << attribute.annotations@AAAAAAFqFYmhNvy4n/8= >>
    // ----------- >>
    private String orderId;

    /**
    * customer visible order reference
    */

    // ----------- << attribute.annotations@AAAAAAFqFYpR3v0BfKA= >>
    // ----------- >>
    private String reference;

    // ----------- << attribute.annotations@AAAAAAFqFYt7Hv7GWEQ= >>
    // ----------- >>
    private String buyerReference;

    @JsonProperty("changed")
    // ----------- << attribute.annotations@AAAAAAFqFYuowP7Nurk= >>
    @JsonDeserialize(using = DateDeserializers.Millis2LocalDateTimeDeserializer.class)
    // ----------- >>
    private LocalDateTime dateOfUpdate;

    // ----------- << attribute.annotations@AAAAAAFqFYweev7XAx0= >>
    // ----------- >>
    private boolean live;

    // ----------- << attribute.annotations@AAAAAAFqFYxChv7e2hE= >>
    // ----------- >>
    private String currency;

    // ----------- << attribute.annotations@AAAAAAFqFYxd1v7lMfU= >>
    // ----------- >>
    private String payoutCurrency;

    /**
    * order total in the transaction's currency
    */

    // ----------- << attribute.annotations@AAAAAAFqFY0TgP7sWRY= >>
    // ----------- >>
    private float total;

    // ----------- << attribute.annotations@AAAAAAFqFY75j/70AFU= >>
    // ----------- >>
    private String totalDisplay;

    // ----------- << attribute.annotations@AAAAAAFqFY8d0P77RjI= >>
    // ----------- >>
    private float totalInPayoutCurrency;

    // ----------- << attribute.annotations@AAAAAAFqFY9JBf8CIoU= >>
    // ----------- >>
    private String totalInPayoutCurrencyDisplay;

    /**
    * amount of tax
    */

    // ----------- << attribute.annotations@AAAAAAFqFY9x2f8JRVA= >>
    // ----------- >>
    private float tax;

    // ----------- << attribute.annotations@AAAAAAFqFY+/Q/8R75s= >>
    // ----------- >>
    private String taxDisplay;

    // ----------- << attribute.annotations@AAAAAAFqFY/e3/8YWcc= >>
    // ----------- >>
    private float taxInPayoutCurrency;

    // ----------- << attribute.annotations@AAAAAAFqFZFLL/8fh2g= >>
    // ----------- >>
    private String taxInPayoutCurrencyDisplay;

    /**
    * order subtotal in the transaction's currency
    */

    // ----------- << attribute.annotations@AAAAAAFqFZFxF/8mtu4= >>
    // ----------- >>
    private float subtotal;

    // ----------- << attribute.annotations@AAAAAAFqFZHejv8u4js= >>
    // ----------- >>
    private String subtotalDisplay;

    // ----------- << attribute.annotations@AAAAAAFqFZIKA/811js= >>
    // ----------- >>
    private float subtotalInPayoutCurrency;

    // ----------- << attribute.annotations@AAAAAAFqFZJLJv88wN8= >>
    // ----------- >>
    private String subtotalInPayoutCurrencyDisplay;

    /**
    * total discount applied to the order in the transaction's currency
    */

    // ----------- << attribute.annotations@AAAAAAFqFZMBOv9HqMc= >>
    // ----------- >>
    private float discount;

    // ----------- << attribute.annotations@AAAAAAFqFZNr1v9PAEI= >>
    // ----------- >>
    private String discountDisplay;

    // ----------- << attribute.annotations@AAAAAAFqGnFCZ60NOS4= >>
    // ----------- >>
    private float discountInPayoutCurrency;

    // ----------- << attribute.annotations@AAAAAAFqGnF0YK19vrg= >>
    // ----------- >>
    private String discountInPayoutCurrencyDisplay;

    /**
    * discount amount including tax
    */

    // ----------- << attribute.annotations@AAAAAAFqFZOHFv9WUKQ= >>
    // ----------- >>
    private float discountWithTax;

    // ----------- << attribute.annotations@AAAAAAFqFZP3s/9e6Eo= >>
    // ----------- >>
    private String discountWithTaxDisplay;

    // ----------- << attribute.annotations@AAAAAAFqFZQYZf9ldSM= >>
    // ----------- >>
    private float discountWithTaxInPayoutCurrency;

    // ----------- << attribute.annotations@AAAAAAFqFZRSB/9s6zI= >>
    // ----------- >>
    private String discountWithTaxInPayoutCurrencyDisplay;

    // ----------- << attribute.annotations@AAAAAAFqFZXh3QBV9Xk= >>
    // ----------- >>
    private String billDescriptor;

    // ----------- << attribute.annotations@AAAAAAFqFZT7sP95+aA= >>
    // ----------- >>
    private CustomerAccount account;

    // ----------- << attribute.annotations@AAAAAAFqFZc26wH4Wk4= >>
    // ----------- >>
    private Payment payment;

    // ----------- << attribute.annotations@AAAAAAFqFZj/sATi8t4= >>
    // ----------- >>
    private Customer customer;

    // ----------- << attribute.annotations@AAAAAAFqFaGQFQsd5dA= >>
    // ----------- >>
    private List<OrderItem> items = new ArrayList<>();

    public String getOrderId() {
        return orderId;
    }

    public String getReference() {
        return reference;
    }

    public String getBuyerReference() {
        return buyerReference;
    }

    public LocalDateTime getDateOfUpdate() {
        return dateOfUpdate;
    }

    public boolean isLive() {
        return live;
    }

    public String getCurrency() {
        return currency;
    }

    public String getPayoutCurrency() {
        return payoutCurrency;
    }

    public float getTotal() {
        return total;
    }

    public String getTotalDisplay() {
        return totalDisplay;
    }

    public float getTotalInPayoutCurrency() {
        return totalInPayoutCurrency;
    }

    public String getTotalInPayoutCurrencyDisplay() {
        return totalInPayoutCurrencyDisplay;
    }

    public float getTax() {
        return tax;
    }

    public String getTaxDisplay() {
        return taxDisplay;
    }

    public float getTaxInPayoutCurrency() {
        return taxInPayoutCurrency;
    }

    public String getTaxInPayoutCurrencyDisplay() {
        return taxInPayoutCurrencyDisplay;
    }

    public float getSubtotal() {
        return subtotal;
    }

    public String getSubtotalDisplay() {
        return subtotalDisplay;
    }

    public float getSubtotalInPayoutCurrency() {
        return subtotalInPayoutCurrency;
    }

    public String getSubtotalInPayoutCurrencyDisplay() {
        return subtotalInPayoutCurrencyDisplay;
    }

    public float getDiscount() {
        return discount;
    }

    public String getDiscountDisplay() {
        return discountDisplay;
    }

    public float getDiscountInPayoutCurrency() {
        return discountInPayoutCurrency;
    }

    public String getDiscountInPayoutCurrencyDisplay() {
        return discountInPayoutCurrencyDisplay;
    }

    public float getDiscountWithTax() {
        return discountWithTax;
    }

    public String getDiscountWithTaxDisplay() {
        return discountWithTaxDisplay;
    }

    public float getDiscountWithTaxInPayoutCurrency() {
        return discountWithTaxInPayoutCurrency;
    }

    public String getDiscountWithTaxInPayoutCurrencyDisplay() {
        return discountWithTaxInPayoutCurrencyDisplay;
    }

    public String getBillDescriptor() {
        return billDescriptor;
    }

    public CustomerAccount getAccount() {
        return account;
    }

    public Payment getPayment() {
        return payment;
    }

    public Customer getCustomer() {
        return customer;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public void setBuyerReference(String buyerReference) {
        this.buyerReference = buyerReference;
    }

    public void setDateOfUpdate(LocalDateTime dateOfUpdate) {
        this.dateOfUpdate = dateOfUpdate;
    }

    public void setLive(boolean live) {
        this.live = live;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public void setPayoutCurrency(String payoutCurrency) {
        this.payoutCurrency = payoutCurrency;
    }

    public void setTotal(float total) {
        this.total = total;
    }

    public void setTotalDisplay(String totalDisplay) {
        this.totalDisplay = totalDisplay;
    }

    public void setTotalInPayoutCurrency(float totalInPayoutCurrency) {
        this.totalInPayoutCurrency = totalInPayoutCurrency;
    }

    public void setTotalInPayoutCurrencyDisplay(String totalInPayoutCurrencyDisplay) {
        this.totalInPayoutCurrencyDisplay = totalInPayoutCurrencyDisplay;
    }

    public void setTax(float tax) {
        this.tax = tax;
    }

    public void setTaxDisplay(String taxDisplay) {
        this.taxDisplay = taxDisplay;
    }

    public void setTaxInPayoutCurrency(float taxInPayoutCurrency) {
        this.taxInPayoutCurrency = taxInPayoutCurrency;
    }

    public void setTaxInPayoutCurrencyDisplay(String taxInPayoutCurrencyDisplay) {
        this.taxInPayoutCurrencyDisplay = taxInPayoutCurrencyDisplay;
    }

    public void setSubtotal(float subtotal) {
        this.subtotal = subtotal;
    }

    public void setSubtotalDisplay(String subtotalDisplay) {
        this.subtotalDisplay = subtotalDisplay;
    }

    public void setSubtotalInPayoutCurrency(float subtotalInPayoutCurrency) {
        this.subtotalInPayoutCurrency = subtotalInPayoutCurrency;
    }

    public void setSubtotalInPayoutCurrencyDisplay(String subtotalInPayoutCurrencyDisplay) {
        this.subtotalInPayoutCurrencyDisplay = subtotalInPayoutCurrencyDisplay;
    }

    public void setDiscount(float discount) {
        this.discount = discount;
    }

    public void setDiscountDisplay(String discountDisplay) {
        this.discountDisplay = discountDisplay;
    }

    public void setDiscountInPayoutCurrency(float discountInPayoutCurrency) {
        this.discountInPayoutCurrency = discountInPayoutCurrency;
    }

    public void setDiscountInPayoutCurrencyDisplay(String discountInPayoutCurrencyDisplay) {
        this.discountInPayoutCurrencyDisplay = discountInPayoutCurrencyDisplay;
    }

    public void setDiscountWithTax(float discountWithTax) {
        this.discountWithTax = discountWithTax;
    }

    public void setDiscountWithTaxDisplay(String discountWithTaxDisplay) {
        this.discountWithTaxDisplay = discountWithTaxDisplay;
    }

    public void setDiscountWithTaxInPayoutCurrency(float discountWithTaxInPayoutCurrency) {
        this.discountWithTaxInPayoutCurrency = discountWithTaxInPayoutCurrency;
    }

    public void setDiscountWithTaxInPayoutCurrencyDisplay(String discountWithTaxInPayoutCurrencyDisplay) {
        this.discountWithTaxInPayoutCurrencyDisplay = discountWithTaxInPayoutCurrencyDisplay;
    }

    public void setBillDescriptor(String billDescriptor) {
        this.billDescriptor = billDescriptor;
    }

    public void setAccount(CustomerAccount account) {
        this.account = account;
    }

    public void setPayment(Payment payment) {
        this.payment = payment;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public void linkAccount(CustomerAccount _account) {
        setAccount(_account);
    }

    public void linkPayment(Payment _payment) {
        setPayment(_payment);
    }

    public void linkCustomer(Customer _customer) {
        setCustomer(_customer);
    }

    public void linkItems(OrderItem _items) {
        if (_items != null) {
            getItems().add(_items);
        }
    }

    public void unlinkAccount() {
        setAccount(null);
    }

    public void unlinkPayment() {
        setPayment(null);
    }

    public void unlinkCustomer() {
        setCustomer(null);
    }

    public void unlinkItems(OrderItem _items) {
        if (_items != null) {
            getItems().remove(_items);
        }
    }

    public void unlinkItems(Iterator<OrderItem> it) {
        it.remove();
    }

// ----------- << class.extras@AAAAAAFqFYFscvvxewM= >>

    @Override
    public String toString() {
        return "OrderCompletedPayload{" +
                "orderId='" + orderId + '\'' +
                ", reference='" + reference + '\'' +
                ", buyerReference='" + buyerReference + '\'' +
                ", dateOfUpdate=" + dateOfUpdate +
                ", live=" + live +
                ", currency='" + currency + '\'' +
                ", payoutCurrency='" + payoutCurrency + '\'' +
                ", total=" + total +
                ", totalDisplay='" + totalDisplay + '\'' +
                ", totalInPayoutCurrency=" + totalInPayoutCurrency +
                ", totalInPayoutCurrencyDisplay='" + totalInPayoutCurrencyDisplay + '\'' +
                ", tax=" + tax +
                ", taxDisplay='" + taxDisplay + '\'' +
                ", taxInPayoutCurrency=" + taxInPayoutCurrency +
                ", taxInPayoutCurrencyDisplay='" + taxInPayoutCurrencyDisplay + '\'' +
                ", subtotal=" + subtotal +
                ", subtotalDisplay='" + subtotalDisplay + '\'' +
                ", subtotalInPayoutCurrency=" + subtotalInPayoutCurrency +
                ", subtotalInPayoutCurrencyDisplay='" + subtotalInPayoutCurrencyDisplay + '\'' +
                ", discount=" + discount +
                ", discountDisplay='" + discountDisplay + '\'' +
                ", discountInPayoutCurrency=" + discountInPayoutCurrency +
                ", discountInPayoutCurrencyDisplay='" + discountInPayoutCurrencyDisplay + '\'' +
                ", discountWithTax=" + discountWithTax +
                ", discountWithTaxDisplay='" + discountWithTaxDisplay + '\'' +
                ", discountWithTaxInPayoutCurrency=" + discountWithTaxInPayoutCurrency +
                ", discountWithTaxInPayoutCurrencyDisplay='" + discountWithTaxInPayoutCurrencyDisplay + '\'' +
                ", billDescriptor='" + billDescriptor + '\'' +
                ", account=" + account +
                ", payment=" + payment +
                ", customer=" + customer +
                ", items=" + items +
                '}';
    }


// ----------- >>
}