/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks.events;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFp+P/bUpPXljw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp+P/bUpPXljw= >>
// ----------- >>
public class Payment {
    // ----------- << attribute.annotations@AAAAAAFp+P/bUpPYMDk= >>
    // ----------- >>
    private String type;

    // ----------- << attribute.annotations@AAAAAAFp+P/bUpPZJGU= >>
    // ----------- >>
    private String creditcard;

    // ----------- << attribute.annotations@AAAAAAFp+P/bUpPa2Wc= >>
    // ----------- >>
    private String cardEnding;

    // ----------- << attribute.annotations@AAAAAAFp+P/bUpPbnig= >>
    // ----------- >>
    private String bank;

    public String getType() {
        return type;
    }

    public String getCreditcard() {
        return creditcard;
    }

    public String getCardEnding() {
        return cardEnding;
    }

    public String getBank() {
        return bank;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setCreditcard(String creditcard) {
        this.creditcard = creditcard;
    }

    public void setCardEnding(String cardEnding) {
        this.cardEnding = cardEnding;
    }

    public void setBank(String bank) {
        this.bank = bank;
    }

// ----------- << class.extras@AAAAAAFp+P/bUpPXljw= >>
// ----------- >>
}