/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks.events;

import java.util.*;
import java.time.*;


import com.archetypesoftware.fastspring.webhooks.WebHookEvent;
// ----------- << imports@AAAAAAFp+P/bQJFbN28= >>
// ----------- >>

/**
* The subscription.charge.completed server webhook event is fired upon completion of a recurring or managed subscription charge,
* or a charge resulting from proration following a subscription upgrade or downgrade.
* 
* For more information, see:
* http://docs.fastspring.com/integrating-with-fastspring/com.archetypesoftware.fastspring.webhooks/subscription-charge-completed
*/

// ----------- << class.annotations@AAAAAAFp+P/bQJFbN28= >>
// ----------- >>
public class SubscriptionChargeCompletedEvent extends WebHookEvent<SubscriptionChargeCompletedPayload> {
// ----------- << class.extras@AAAAAAFp+P/bQJFbN28= >>
// ----------- >>
}