/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks.events;

import java.util.*;
import java.time.*;


import com.archetypesoftware.fastspring.webhooks.EventPayload;
// ----------- << imports@AAAAAAFp+P/bS5KHX50= >>
import com.archetypesoftware.fastspring.webhooks.EventPayload;
import com.archetypesoftware.jackson.DateDeserializers;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
// ----------- >>

/**
* Payload of the SubscriptionChargeCompleted Event.
*/

// ----------- << class.annotations@AAAAAAFp+P/bS5KHX50= >>
// ----------- >>
public class SubscriptionChargeCompletedPayload extends EventPayload {
    // ----------- << attribute.annotations@AAAAAAFp+P/bS5KSlLI= >>
    // ----------- >>
    private String currency;

    // ----------- << attribute.annotations@AAAAAAFp+P/bS5KTvOY= >>
    // ----------- >>
    private float total;

    // ----------- << attribute.annotations@AAAAAAFp+P/bS5KUEcU= >>
    // ----------- >>
    private String status;

    // ----------- << attribute.annotations@AAAAAAFp+P/bS5KVIp4= >>
    @JsonDeserialize(using = DateDeserializers.Millis2LocalDateTimeDeserializer.class)
    // ----------- >>
    private LocalDateTime timestamp;

    // ----------- << attribute.annotations@AAAAAAFp+P/bS5KWTo0= >>
    // ----------- >>
    private int sequence;

    // ----------- << attribute.annotations@AAAAAAFp+P/bS5KLzOY= >>
    // ----------- >>
    private Order order;

    // ----------- << attribute.annotations@AAAAAAFp+P/bS5KOuPI= >>
    // ----------- >>
    private CustomerAccount account;

    // ----------- << attribute.annotations@AAAAAAFp+P/bS5KRCE0= >>
    // ----------- >>
    private Subscription subscription;

    public String getCurrency() {
        return currency;
    }

    public float getTotal() {
        return total;
    }

    public String getStatus() {
        return status;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public int getSequence() {
        return sequence;
    }

    public Order getOrder() {
        return order;
    }

    public CustomerAccount getAccount() {
        return account;
    }

    public Subscription getSubscription() {
        return subscription;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public void setTotal(float total) {
        this.total = total;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public void setSequence(int sequence) {
        this.sequence = sequence;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    public void setAccount(CustomerAccount account) {
        this.account = account;
    }

    public void setSubscription(Subscription subscription) {
        this.subscription = subscription;
    }

    public void linkOrder(Order _order) {
        setOrder(_order);
    }

    public void linkAccount(CustomerAccount _account) {
        setAccount(_account);
    }

    public void linkSubscription(Subscription _subscription) {
        setSubscription(_subscription);
    }

    public void unlinkOrder() {
        setOrder(null);
    }

    public void unlinkAccount() {
        setAccount(null);
    }

    public void unlinkSubscription() {
        setSubscription(null);
    }

// ----------- << class.extras@AAAAAAFp+P/bS5KHX50= >>

    @Override
    public String toString() {
        return "SubscriptionChargeCompletedPayload{" +
                "currency='" + currency + '\'' +
                ", total=" + total +
                ", status='" + status + '\'' +
                ", timestamp=" + timestamp +
                ", sequence=" + sequence +
                ", order=" + order +
                ", account=" + account +
                ", subscription=" + subscription +
                '}';
    }

// ----------- >>
}