/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks.events;

import java.util.*;
import java.time.*;

import com.fasterxml.jackson.annotation.*;


// ----------- << imports@AAAAAAFp+P/bVJP2oWU= >>
import com.archetypesoftware.jackson.DateDeserializers;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
// ----------- >>

@JsonIgnoreProperties(ignoreUnknown = true)
// ----------- << class.annotations@AAAAAAFp+P/bVJP2oWU= >>
// ----------- >>
public class Subscription {
    // ----------- << attribute.annotations@AAAAAAFp+P/bVJP319A= >>
    // ----------- >>
    private String id;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJP4E4k= >>
    // ----------- >>
    private boolean active;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJP50lw= >>
    // ----------- >>
    private String state;

    @JsonProperty("changed")
    // ----------- << attribute.annotations@AAAAAAFp+P/bVJP6U9I= >>
    @JsonDeserialize(using = DateDeserializers.Millis2LocalDateTimeDeserializer.class)
    // ----------- >>
    private LocalDateTime dateOfLastUpdate;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJP8hVM= >>
    // ----------- >>
    private boolean live;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJP9AiE= >>
    // ----------- >>
    private String currency;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJP+CB8= >>
    // ----------- >>
    private String account;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJP/7Gg= >>
    // ----------- >>
    private String product;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQABlw= >>
    // ----------- >>
    private String sku;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQBl9I= >>
    // ----------- >>
    private String display;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQCC/4= >>
    // ----------- >>
    private int quantity;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQDn2c= >>
    // ----------- >>
    private boolean adhoc;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQEv5Q= >>
    // ----------- >>
    private boolean autoRenew;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQFPFg= >>
    // ----------- >>
    private float price;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQGaic= >>
    // ----------- >>
    private String priceDisplay;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQHPPw= >>
    // ----------- >>
    private float priceInPayoutCurrency;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQIJcM= >>
    // ----------- >>
    private float discount;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQJe1Y= >>
    // ----------- >>
    private String discountDisplay;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQKRzo= >>
    // ----------- >>
    private float discountInPayoutCurrency;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVJQL/K0= >>
    // ----------- >>
    private float subtotal;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQM1fk= >>
    // ----------- >>
    private String subtotalDisplay;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQNKD0= >>
    // ----------- >>
    private float subtotalInPayoutCurrency;

    @JsonProperty("next")
    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQOJB4= >>
    @JsonDeserialize(using = DateDeserializers.Millis2LocalDateTimeDeserializer.class)
    // ----------- >>
    private LocalDateTime dateOfNextCharge;

    @JsonProperty("nextDisplay")
    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQQBVY= >>
    // ----------- >>
    private String dateOfNextChargeDisplay;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQSJQU= >>
    @JsonDeserialize(using = DateDeserializers.Millis2LocalDateTimeDeserializer.class)
    // ----------- >>
    private LocalDateTime canceledDate;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQT2/k= >>
    @JsonDeserialize(using = DateDeserializers.Millis2LocalDateTimeDeserializer.class)
    // ----------- >>
    private LocalDateTime deactivationDate;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQUXm8= >>
    // ----------- >>
    private int sequence;

    @JsonProperty("begin")
    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQVSEM= >>
    @JsonDeserialize(using = DateDeserializers.Millis2LocalDateTimeDeserializer.class)
    // ----------- >>
    private LocalDateTime validFrom;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQX8fg= >>
    // ----------- >>
    private String intervalUnit;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQYKlo= >>
    // ----------- >>
    private int intervalLength;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQZlXY= >>
    // ----------- >>
    private String nextChargeCurrency;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQaqDg= >>
    @JsonDeserialize(using = DateDeserializers.Millis2LocalDateTimeDeserializer.class)
    // ----------- >>
    private LocalDateTime nextChargeDate;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQbzU4= >>
    // ----------- >>
    private String nextChargeDateDisplay;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQcMmc= >>
    // ----------- >>
    private float nextChargeTotal;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQdlnU= >>
    // ----------- >>
    private String nextChargeTotalDisplay;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQeYDc= >>
    // ----------- >>
    private float nextChargeTotalInPayoutCurrency;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQfy4U= >>
    // ----------- >>
    private String nextNotificationType;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQgtcM= >>
    @JsonDeserialize(using = DateDeserializers.Millis2LocalDateTimeDeserializer.class)
    // ----------- >>
    private LocalDateTime nextNotificationDate;

    // ----------- << attribute.annotations@AAAAAAFp+P/bVZQhvUU= >>
    // ----------- >>
    private String nextNotificationDateDisplay;

    public String getId() {
        return id;
    }

    public boolean isActive() {
        return active;
    }

    public String getState() {
        return state;
    }

    public LocalDateTime getDateOfLastUpdate() {
        return dateOfLastUpdate;
    }

    public boolean isLive() {
        return live;
    }

    public String getCurrency() {
        return currency;
    }

    public String getAccount() {
        return account;
    }

    public String getProduct() {
        return product;
    }

    public String getSku() {
        return sku;
    }

    public String getDisplay() {
        return display;
    }

    public int getQuantity() {
        return quantity;
    }

    public boolean isAdhoc() {
        return adhoc;
    }

    public boolean isAutoRenew() {
        return autoRenew;
    }

    public float getPrice() {
        return price;
    }

    public String getPriceDisplay() {
        return priceDisplay;
    }

    public float getPriceInPayoutCurrency() {
        return priceInPayoutCurrency;
    }

    public float getDiscount() {
        return discount;
    }

    public String getDiscountDisplay() {
        return discountDisplay;
    }

    public float getDiscountInPayoutCurrency() {
        return discountInPayoutCurrency;
    }

    public float getSubtotal() {
        return subtotal;
    }

    public String getSubtotalDisplay() {
        return subtotalDisplay;
    }

    public float getSubtotalInPayoutCurrency() {
        return subtotalInPayoutCurrency;
    }

    public LocalDateTime getDateOfNextCharge() {
        return dateOfNextCharge;
    }

    public String getDateOfNextChargeDisplay() {
        return dateOfNextChargeDisplay;
    }

    public LocalDateTime getCanceledDate() {
        return canceledDate;
    }

    public LocalDateTime getDeactivationDate() {
        return deactivationDate;
    }

    public int getSequence() {
        return sequence;
    }

    public LocalDateTime getValidFrom() {
        return validFrom;
    }

    public String getIntervalUnit() {
        return intervalUnit;
    }

    public int getIntervalLength() {
        return intervalLength;
    }

    public String getNextChargeCurrency() {
        return nextChargeCurrency;
    }

    public LocalDateTime getNextChargeDate() {
        return nextChargeDate;
    }

    public String getNextChargeDateDisplay() {
        return nextChargeDateDisplay;
    }

    public float getNextChargeTotal() {
        return nextChargeTotal;
    }

    public String getNextChargeTotalDisplay() {
        return nextChargeTotalDisplay;
    }

    public float getNextChargeTotalInPayoutCurrency() {
        return nextChargeTotalInPayoutCurrency;
    }

    public String getNextNotificationType() {
        return nextNotificationType;
    }

    public LocalDateTime getNextNotificationDate() {
        return nextNotificationDate;
    }

    public String getNextNotificationDateDisplay() {
        return nextNotificationDateDisplay;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public void setState(String state) {
        this.state = state;
    }

    public void setDateOfLastUpdate(LocalDateTime dateOfLastUpdate) {
        this.dateOfLastUpdate = dateOfLastUpdate;
    }

    public void setLive(boolean live) {
        this.live = live;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public void setDisplay(String display) {
        this.display = display;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public void setAdhoc(boolean adhoc) {
        this.adhoc = adhoc;
    }

    public void setAutoRenew(boolean autoRenew) {
        this.autoRenew = autoRenew;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public void setPriceDisplay(String priceDisplay) {
        this.priceDisplay = priceDisplay;
    }

    public void setPriceInPayoutCurrency(float priceInPayoutCurrency) {
        this.priceInPayoutCurrency = priceInPayoutCurrency;
    }

    public void setDiscount(float discount) {
        this.discount = discount;
    }

    public void setDiscountDisplay(String discountDisplay) {
        this.discountDisplay = discountDisplay;
    }

    public void setDiscountInPayoutCurrency(float discountInPayoutCurrency) {
        this.discountInPayoutCurrency = discountInPayoutCurrency;
    }

    public void setSubtotal(float subtotal) {
        this.subtotal = subtotal;
    }

    public void setSubtotalDisplay(String subtotalDisplay) {
        this.subtotalDisplay = subtotalDisplay;
    }

    public void setSubtotalInPayoutCurrency(float subtotalInPayoutCurrency) {
        this.subtotalInPayoutCurrency = subtotalInPayoutCurrency;
    }

    public void setDateOfNextCharge(LocalDateTime dateOfNextCharge) {
        this.dateOfNextCharge = dateOfNextCharge;
    }

    public void setDateOfNextChargeDisplay(String dateOfNextChargeDisplay) {
        this.dateOfNextChargeDisplay = dateOfNextChargeDisplay;
    }

    public void setCanceledDate(LocalDateTime canceledDate) {
        this.canceledDate = canceledDate;
    }

    public void setDeactivationDate(LocalDateTime deactivationDate) {
        this.deactivationDate = deactivationDate;
    }

    public void setSequence(int sequence) {
        this.sequence = sequence;
    }

    public void setValidFrom(LocalDateTime validFrom) {
        this.validFrom = validFrom;
    }

    public void setIntervalUnit(String intervalUnit) {
        this.intervalUnit = intervalUnit;
    }

    public void setIntervalLength(int intervalLength) {
        this.intervalLength = intervalLength;
    }

    public void setNextChargeCurrency(String nextChargeCurrency) {
        this.nextChargeCurrency = nextChargeCurrency;
    }

    public void setNextChargeDate(LocalDateTime nextChargeDate) {
        this.nextChargeDate = nextChargeDate;
    }

    public void setNextChargeDateDisplay(String nextChargeDateDisplay) {
        this.nextChargeDateDisplay = nextChargeDateDisplay;
    }

    public void setNextChargeTotal(float nextChargeTotal) {
        this.nextChargeTotal = nextChargeTotal;
    }

    public void setNextChargeTotalDisplay(String nextChargeTotalDisplay) {
        this.nextChargeTotalDisplay = nextChargeTotalDisplay;
    }

    public void setNextChargeTotalInPayoutCurrency(float nextChargeTotalInPayoutCurrency) {
        this.nextChargeTotalInPayoutCurrency = nextChargeTotalInPayoutCurrency;
    }

    public void setNextNotificationType(String nextNotificationType) {
        this.nextNotificationType = nextNotificationType;
    }

    public void setNextNotificationDate(LocalDateTime nextNotificationDate) {
        this.nextNotificationDate = nextNotificationDate;
    }

    public void setNextNotificationDateDisplay(String nextNotificationDateDisplay) {
        this.nextNotificationDateDisplay = nextNotificationDateDisplay;
    }

// ----------- << class.extras@AAAAAAFp+P/bVJP2oWU= >>

    @Override
    public String toString() {
        return "Subscription{" +
                "id='" + id + '\'' +
                ", active=" + active +
                ", state='" + state + '\'' +
                ", dateOfLastUpdate=" + dateOfLastUpdate +
                ", live=" + live +
                ", currency='" + currency + '\'' +
                ", account='" + account + '\'' +
                ", product='" + product + '\'' +
                ", sku='" + sku + '\'' +
                ", display='" + display + '\'' +
                ", quantity=" + quantity +
                ", adhoc=" + adhoc +
                ", autoRenew=" + autoRenew +
                ", price=" + price +
                ", priceDisplay='" + priceDisplay + '\'' +
                ", priceInPayoutCurrency=" + priceInPayoutCurrency +
                ", discount=" + discount +
                ", discountDisplay='" + discountDisplay + '\'' +
                ", discountInPayoutCurrency=" + discountInPayoutCurrency +
                ", subtotal=" + subtotal +
                ", subtotalDisplay='" + subtotalDisplay + '\'' +
                ", subtotalInPayoutCurrency=" + subtotalInPayoutCurrency +
                ", dateOfNextCharge=" + dateOfNextCharge +
                ", dateOfNextChargeDisplay='" + dateOfNextChargeDisplay + '\'' +
                ", canceledDate=" + canceledDate +
                ", deactivationDate=" + deactivationDate +
                ", sequence=" + sequence +
                ", validFrom=" + validFrom +
                ", intervalUnit='" + intervalUnit + '\'' +
                ", intervalLength=" + intervalLength +
                ", nextChargeCurrency='" + nextChargeCurrency + '\'' +
                ", nextChargeDate=" + nextChargeDate +
                ", nextChargeDateDisplay='" + nextChargeDateDisplay + '\'' +
                ", nextChargeTotal=" + nextChargeTotal +
                ", nextChargeTotalDisplay='" + nextChargeTotalDisplay + '\'' +
                ", nextChargeTotalInPayoutCurrency=" + nextChargeTotalInPayoutCurrency +
                ", nextNotificationType='" + nextNotificationType + '\'' +
                ", nextNotificationDate=" + nextNotificationDate +
                ", nextNotificationDateDisplay='" + nextNotificationDateDisplay + '\'' +
                '}';
    }


// ----------- >>
}