/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks.events;

import java.util.*;
import java.time.*;


import com.archetypesoftware.fastspring.webhooks.WebHookEvent;
// ----------- << imports@AAAAAAFp+P/bQJFXvsg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp+P/bQJFXvsg= >>
// ----------- >>
public class SubscriptionActivatedEvent extends WebHookEvent<SubscriptionActivatedPayload> {
// ----------- << class.extras@AAAAAAFp+P/bQJFXvsg= >>
// ----------- >>
}