/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks.events;

import java.util.*;
import java.time.*;


import com.archetypesoftware.fastspring.webhooks.WebHookEvent;
import com.archetypesoftware.fastspring.webhooks.EventVisitor;
// ----------- << imports@AAAAAAFp+P/bQJFfKH8= >>
// ----------- >>

/**
* The subscription.deactivated server webhook event is fired upon deactivation of a subscription, 
* including deactivation at the end of the billing period following a prior cancellation, or immediately upon 
* cancellation when a subscription is canceled with the Deactivate Now option selected (via Dashboard) or the 
* billingPeriod=0 parameter is included (canceling via the /subscriptions endpoint of the FastSpring API). 
* 
* For more information, see:
* http://docs.fastspring.com/integrating-with-fastspring/webhooks/subscription-deactivated
*/

// ----------- << class.annotations@AAAAAAFp+P/bQJFfKH8= >>
// ----------- >>
public class SubscriptionDeactivatedEvent extends WebHookEvent<SubscriptionDeactivatedPayload> {
    /**
    * @param visitor
    */

    // ----------- << method.annotations@AAAAAAFqAbICmPfer7Q= >>
    // ----------- >>
    public void accept(EventVisitor visitor) {
    // ----------- << method.body@AAAAAAFqAbICmPfer7Q= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAFp+P/bQJFfKH8= >>
// ----------- >>
}