/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetypesoftware.fastspring.webhooks.events;


// ----------- << imports@AAAAAAFp+P/bQZFje7I= >>
// ----------- >>

import com.archetypesoftware.fastspring.webhooks.WebHookEvent;

// ----------- << class.annotations@AAAAAAFp+P/bQZFje7I= >>
// ----------- >>
public class SubscriptionPaymentOverdueEvent extends WebHookEvent {
// ----------- << class.extras@AAAAAAFp+P/bQZFje7I= >>
// ----------- >>
}